% Create a dipole antenna
% Generated by MATLAB(R) 9.11 and Antenna Toolbox 5.1.
% Generated on: 19-Apr-2022 19:32:38

%% Antenna Properties 

antennaObject = design(dipole, 386*1e6);
antennaObject.Conductor.Name = 'Aluminium';
antennaObject.Conductor.Conductivity = 3.77*1e7;
antennaObject.Conductor.Thickness = 0.000762;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 386*1e6;
% Define frequency range 
freqRange = (347.4:3.86:424.6)*1e6;
% sparameter
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s)
% pattern
figure;
pattern(antennaObject, plotFrequency)

